# If not running interactively, quit now
[ -z "$PS1" ] && return


# python and pip
export PYTHONSTARTUP=~/.pythonstartup.py
export PIP_REQUIRE_VIRTUALENV=true
alias syspip='PIP_REQUIRE_VIRTUALENV= pip'

GIT_LOG_FORMAT="%C(yellow)%h%C(reset) %C(blue)%an"
GIT_LOG_FORMAT+=" %C(green)%ad%C(red)%d%C(reset)
        %s"
export GIT_LOG_FORMAT


# aliases: ls
alias ll='ls -l'


# aliases: foreman
alias fr='foreman run'
alias fs='foreman start'


# aliases: git
alias g='git'
alias gs='git status'
alias gd='git diff'
alias ga='git add --all'
alias gaa='ga :/'
alias gr='git reset'
alias grh='gr --hard'
alias gco='git checkout'
alias gc='git commit --verbose'
alias gca='gc --all'
alias gm='gc --amend'
alias gma='gm --all'
alias gp='git diff --cached'
alias gdw='gd --word-diff=color'
alias gpw='gp --word-diff=color'
alias gf='git fetch'
alias gpp='git pull; git push'
GLL='git log --graph --branches --remotes --abbrev-commit '
GLL+='--date=relative --decorate --pretty=format:"$GIT_LOG_FORMAT"'
alias gll=$GLL
alias gl='gll -10'
alias gj='git merge --no-ff'
alias gff='git merge --ff-only'
alias gmv='git mv'
alias grm='git rm'
alias gri='git rebase'
alias gri='gr --interactive'
alias gra='gr --abort'
alias grc='gr --continue'
alias gt='git stash'
gignoredir () {
    echo '*' > "$1/.gitignore";
}


# local zsh file
test -f $HOME/.zsh_localrc && source $HOME/.zsh_localrc
